<<<<<<< HEAD
baseURL = "https://links.jelsamina.com"
=======
baseURL = "https://links.jelsamina.com/"
>>>>>>> 9317671 (let's try this again)
languageCode = "en"
defaultContentLanguage = "en"
theme = "lynx"

title = "Jelsamina"
<<<<<<< HEAD
# copyright = "Copy, _right?_ :thinking_face:"
copyright = "Â© 2025 Jelsamina"

enableEmoji = true
disableKinds = ["taxonomy", "term", "RSS", "sitemap"]

[params.author]
  name = "Jelsamina"
  headline = ""
  #image = "img/author.jpg"  # path relative to static directory

  links = [
     { email = "mailto:example@example.com" },
     { link = "https://jelsamina.com/" },
     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { bandcamp = "https://username.bandcamp.com" },
     { bluesky = "https://bsky.app/profile/username" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
     { discord = "https://discord.gg/invitecode" },
=======
copyright = "&copy; 2025 Jelsamina"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
   name = "Jelsamina"
   headline = "An awesome person"
   #image = "img/author.jpg"  # path relative to static directory

  links = [
    { email = "mailto:example@example.com" },
    { link = "https://jelsamina.com/" },
    { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { bandcamp = "https://username.bandcamp.com" },
    { bluesky = "https://bsky.app/profile/username" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    { discord = "https://discord.gg/invitecode" },
>>>>>>> 9317671 (let's try this again)
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    # { github = "https://github.com/username" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    { instagram = "https://instagram.com/username" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://last.fm/user/username" },
<<<<<<< HEAD
     { linkedin = "https://linkedin.com/in/username" },
=======
    { linkedin = "https://linkedin.com/in/username" },
>>>>>>> 9317671 (let's try this again)
    # { mastodon = "https://mastodon.instance/@username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
<<<<<<< HEAD
     { snapchat = "https://snapchat.com/add/username" },
=======
    { snapchat = "https://snapchat.com/add/username" },
>>>>>>> 9317671 (let's try this again)
    # { soundcloud = "https://soundcloud.com/username" },
    # { spotify = "https://spotify.com/user/username" },
    # { stack-exchange = "https://stackexchange.com/users/userid/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    # { threads = "https://threads.com/username" },
<<<<<<< HEAD
     { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
     { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { x = "https://x.com/username" },
     { youtube = "https://youtube.com/username" },
=======
    { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { x = "https://x.com/username" },
    { youtube = "https://youtube.com/username" },
>>>>>>> 9317671 (let's try this again)
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
